---
- name: Deploy app
  hosts: workers
  remote_user: ansible
  become: yes
  become_method: sudo
  roles:
  - { role: init, tags: init }
  - { role: docker, tags: docker }
  - { role: app, tags: app }
