name: 'CD'

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Image tag to deploy'
        required: true
        type: string

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.image_tag.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Get image tag
      id: image_tag
      run: |
        tag=`git log -n1 --format='%B' --no-merges HEAD | awk '/image_tag/ {$1="";print}'|tr -d ' '`
        echo "tag=$tag" >> $GITHUB_OUTPUT
  run:
    if: github.event.pull_request.merged == true && ( needs.check_tag.outputs.TAG != '' || inputs.TAG != '' )
    needs: check_tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.check_tag.outputs.TAG || inputs.TAG }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}
    - name: Deploy
      run: |
        echo ${{ secrets.VAULT_PASSWORD }} > vault_file
        ansible-playbook -i inventory/worker_hosts playbook/app.yaml --extra-vars "APP_IMAGE_TAG=`echo ${{ env.TAG }}`" --vault-password-file vault_file -vv

